workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - build-test
  - docker
  - pages

default:
  interruptible: true

include:
  - local: .gitlab/ci/api.yml
  - local: .gitlab/ci/web.yml
  - local: .gitlab/ci/e2e.yml
  - local: .gitlab/ci/docs.yml
