apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: {{ .Release.Namespace }}
data:
  alertmanager.yml: |
{{ tpl (.Files.Get "files/alertmanager/alertmanager.yml") . | indent 4 }}
