apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasources
  namespace: {{ .Release.Namespace }}
data:
  datasources.yaml: |
{{ .Files.Get "files/grafana-datasources.yaml" | indent 4 }}
  datasources-tempo.yaml: |
{{ .Files.Get "files/grafana-datasources-tempo.yaml" | indent 4 }}
