apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seq-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.storage.seq}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
        - name: seq
          image: datalust/seq:2024.3
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: BASE_URI_PATH
              value: /seq
            - name: SEQ_FIRSTRUN_ADMINUSERNAME
              value: admin
            - name: SEQ_FIRSTRUN_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: testcraft-secrets
                  key: SEQ_ADMIN_PASSWORD
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: 256Mi
              cpu: "100m"
            limits:
              memory: 1Gi
              cpu: "1"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: seq-data
---
apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: seq
  ports:
    - port: 80
      targetPort: 80
