<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
    <VSTestLogger>
      junit%3BLogFilePath=$(MSBuildThisFileDirectory)../../test-results/$(MSBuildProjectName).junit.xml;testcraft</VSTestLogger>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="JunitXml.TestLogger" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TestCraft.Api\TestCraft.Api.csproj" />
    <ProjectReference Include="..\..\src\TestCraft.Domain\TestCraft.Domain.csproj" />
    <ProjectReference Include="..\..\src\TestCraft.Application\TestCraft.Application.csproj" />
    <ProjectReference Include="..\..\src\TestCraft.Infrastructure\TestCraft.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\tools\TestCraft.VSTestLogger\TestCraft.VSTestLogger.csproj" />
  </ItemGroup>
</Project>
