import type { TestResultStatus } from '@testcraft/types';

import { StatusBadge } from '@/components/ui/StatusBadge';
import { useSharedRun } from '@/features/shareTokens/hooks';
import { useRequiredParam } from '@/hooks/useRequiredParam';
import { cn } from '@/lib/cn';
import {
  formatDate,
  formatDateTime,
  formatDuration,
  passRateClass,
} from '@/lib/format';

export const SharePage = () => {
  const token = useRequiredParam('token');
  const { data: run, isPending, isError } = useSharedRun(token);

  if (isPending)
    return (
      <div className="flex min-h-screen items-center justify-center">
        <span className="loading loading-lg loading-spinner text-primary" />
      </div>
    );

  if (isError || !run)
    return (
      <div className="flex min-h-screen items-center justify-center p-8">
        <div className="text-center">
          <h1 className="mb-2 text-2xl font-bold text-error">Link not found</h1>
          <p className="text-sm text-base-content/85">
            This share link may have expired or been revoked.
          </p>
        </div>
      </div>
    );

  return (
    <div className="min-h-screen bg-base-200">
      <div className="mx-auto max-w-4xl px-4 py-10">
        <div className="mb-2 flex items-center gap-2">
          <span className="text-xs font-semibold tracking-widest text-base-content/65 uppercase">
            Shared Test Run
          </span>
        </div>
        <h1 className="font-display text-3xl font-bold tracking-tight">
          {run.runName}
        </h1>
        {run.environment && (
          <p className="mt-1 text-sm text-base-content/85">{run.environment}</p>
        )}
        <p className="mt-1 text-xs text-base-content/65">
          {formatDate(run.createdAt)}
        </p>

        <div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-5">
          <Stat label="Total" value={run.total} />
          <Stat label="Passed" value={run.passed} className="text-success" />
          <Stat label="Failed" value={run.failed} className="text-error" />
          <Stat label="Blocked" value={run.blocked} className="text-warning" />
          <Stat
            label="Skipped"
            value={run.skipped}
            className="text-base-content/75"
          />
        </div>
        <div className="mt-3">
          <span
            className={cn('text-xl font-bold', passRateClass(run.passRate))}
          >
            {run.passRate}%
          </span>
          <span className="ml-1.5 text-sm text-base-content/75">pass rate</span>
        </div>

        <div className="mt-8 overflow-x-auto rounded-xl border border-border bg-base-100">
          <table className="table">
            <thead>
              <tr className="text-xs text-base-content/85">
                <th>#</th>
                <th>Test Case</th>
                <th>Status</th>
                <th>Duration</th>
                <th>Executed</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
              {(run.results ?? []).map((result, index) => (
                <tr key={`${result.testCaseName}-${index}`} className="hover">
                  <td className="text-xs text-base-content/65 tabular-nums">
                    {index + 1}
                  </td>
                  <td className="text-sm font-medium">{result.testCaseName}</td>
                  <td>
                    <StatusBadge status={result.status as TestResultStatus} />
                  </td>
                  <td className="text-xs text-base-content/75 tabular-nums">
                    {formatDuration(result.durationMs)}
                  </td>
                  <td className="text-xs whitespace-nowrap text-base-content/75 tabular-nums">
                    {formatDateTime(result.executedAt)}
                  </td>
                  <td className="max-w-xs truncate text-xs text-base-content/85">
                    {result.notes ?? '—'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <p className="mt-8 text-center text-xs text-base-content/55">
          Generated by TestCraft
        </p>
      </div>
    </div>
  );
};

const Stat = ({
  label,
  value,
  className,
}: {
  label: string;
  value: number;
  className?: string;
}) => (
  <div className="rounded-xl border border-border bg-base-100 p-4 text-center">
    <p className={cn('text-2xl font-bold tabular-nums', className)}>{value}</p>
    <p className="mt-0.5 text-xs text-base-content/75">{label}</p>
  </div>
);
