<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <!-- CA1707: underscores are idiomatic for xUnit test names. -->
    <NoWarn>$(NoWarn);CA1707</NoWarn>
    <VSTestLogger>junit%3BLogFilePath=$(MSBuildThisFileDirectory)../../test-results/junit.xml</VSTestLogger>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="JunitXml.TestLogger" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TestCraft.Application\TestCraft.Application.csproj" />
    <ProjectReference Include="..\..\src\TestCraft.Infrastructure\TestCraft.Infrastructure.csproj" />
  </ItemGroup>
</Project>
