images:
  api:
    repository: ghcr.io/nevalenti/testcraft-api
    pullPolicy: Always
  web:
    repository: ghcr.io/nevalenti/testcraft-web
    pullPolicy: Always
  gateway:
    repository: ghcr.io/nevalenti/testcraft-gateway
    pullPolicy: Always
  docs:
    repository: ghcr.io/nevalenti/testcraft-docs
    pullPolicy: Always

tls:
  provider: letsencrypt

storage:
  tempo: 5Gi

ingress-nginx:
  enabled: true
  fullnameOverride: acme-solver
  controller:
    service:
      type: ClusterIP
    ingressClassResource:
      name: nginx-acme
      default: false
    ingressClass: nginx-acme
    watchIngressWithoutClass: false
    admissionWebhooks:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
