global:
  resolve_timeout: 5m
  smtp_smarthost: '{{ .Values.secrets.smtpHost }}:{{ .Values.secrets.smtpPort }}'
  smtp_from: '{{ .Values.secrets.smtpFromAddress }}'
  smtp_auth_username: '{{ .Values.secrets.smtpUser }}'
  smtp_auth_password_file: /etc/alertmanager/secrets/smtp-password
  smtp_require_tls: true

route:
  receiver: email
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: email
    email_configs:
      - to: '{{ .Values.secrets.alertEmailTo }}'
        send_resolved: true

inhibit_rules:
  - source_matchers: ["severity = critical"]
    target_matchers: ["severity = warning"]
    equal: ["alertname", "instance"]
