<Project Sdk="Microsoft.NET.Sdk.Web">
  
  <ItemGroup>
    <ProjectReference Include="../Application/Application.csproj" />
    <ProjectReference Include="../Infrastructure/Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup Label="Validation">
    <PackageReference Include="FluentValidation.AspNetCore" />
  </ItemGroup>
  
  <ItemGroup Label="Logging">
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

  <ItemGroup Label="EF Core">
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Label="OpenAPI">
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

</Project>
