apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    uid: alertmanager
    jsonData:
      implementation: prometheus

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{app="testcraft-api"} |= "${__trace.traceId}"'
