#!/usr/bin/env bash

set -euo pipefail

VALUES_FILE="infrastructure/helm/testcraft/values.yaml"
OUT_FILE="infrastructure/image-versions.env"

{
  echo "# Generated by scripts/render-image-versions.sh from ${VALUES_FILE}. Do not edit by hand."
  yq e '.thirdPartyImages | to_entries | .[] | (.key | upcase) + "_IMAGE=" + .value' "$VALUES_FILE"
} > "$OUT_FILE"
